before:
  hooks:
    - go mod tidy
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
  sort: asc
  filters:
    exclude: # exclude commit messages from the changelog
      - "^docs"

builds:
  - main: ./cmd/
    env:
      - CGO_ENABLED=0
    hooks:
      post: rice append --exec /board
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates: ["ghcr.io/trifork/tcs-board:{{ .Version }}"]
    dockerfile: .goreleaser.dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/trifork/tcs-board
      - --label=org.opencontainers.image.source=https://github.com/trifork/tcs-board
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
