language: go

go:
  - 1.12.x

install: true

git:
  depth: 1

env:
  - GO111MODULE=on

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - golangci-lint run       # Run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled

notifications:
  email: false
