language: go

go:
  - 1.6

go_import_path: board

install:
  - cp config.sample config.go
  - go install ./...

script:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - gometalinter --deadline 100s -t -E misspell -E gofmt --skip vendor ./...
