AutoDiscover:
  Ingres: true

Services:
  - Name: Lesterpig.com
    Category: Web
    Probe: http
    Config:
      Target: https://www.lesterpig.com
      Options:
        Regex: Loïck Bonniot
  - Name: SMTP
    Category: Services
    Probe: smtp
    Config:
      Warning: 10s
      Fatal: 15s
      Target: mail.google.com:465

Alerts:
  - Type: pushbullet
    Token: <your token here>
  # ...
